sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    ‐ hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: haijiandong/haijiandong.github.io
    fqdn: http://www.hais2.com
    target_branch: master
    email: haijiandong@outlook.com
    name: haijiandong