baseURL = "/"
# remember trailing / at end of baseurl
languageCode = "en-us"
title = "Haijd's Blog"
# Enable comments by entering your Disqus shortname
disqusShortname = "HaijdBlog"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 20
theme = "sublime-hugo-theme"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Haijd"
	description = "a coder."
	copyright = "Haijd"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Haijd's Blog"
	bio = "one coder."
	bio2 = "beijing china"
  	categories = "CATEGORIES"
  	tags = "TAGS"
	subscribe = "LOOK ME."

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "EMAIL"
		url = "mailto:haijiandong@outlook.com"
  [[params.offcanvas.socialnetworks]]
		name = "GITHUB"
		url = "https://github.com/hjdo"
