baseURL = "http://www.hais2.com"
languageCode = "en-us"
title = "Haijd's Blog"
theme = "hugo-theme-cleanwhite"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 10
# optionally override the site's footer with custom copyright text
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
# googleAnalytics = "UA-123-45"
disqusShortname = "haijdblog"
googleAnalytics = ""
preserveTaxonomyNames = true
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]


[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "海建东的博客 | haijd's Blog"
  description = "海建东 | 欢迎访问我的博客，希望能和你交个朋友。"
  keyword = "海建东, haijiandong, HaiJianDong, , Haijd, _Is2, Is2, 海建东的博客, Haijd Blog, 博客, 个人网站, 互联网, Web, 微服务, Microservice, golang , .Net, Java"
  slogan = "Done is better than perfect."

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false 
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "一只努力奋斗的码农"
  sidebar_avatar = "img/avatar-haijd.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  rss            = true 
  email          = "haijiandong@outlook.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "full profile url in linkedin"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/haijiandong"
  wechat         = "404455292"
  #pinterest     = "full profile url in pinterest"
  
#   [[params.friend_link]]
#   title = "Linda的博客"
#   href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 